[project]
name = "hyperliquid-mcp-python"
version = "0.1.0"
description = "HyperLiquid MCP Server with FastMCP - Trading tools and account management"
authors = [
    {name = "Gigabrain", email = "chetan@gigabrain.gg"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.9.2",
    "hyperliquid-python-sdk>=0.15.0",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "eth-account>=0.10.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "isort>=5.0",
]

[project.scripts]
hyperliquid-mcp = "cli:main"
start = "main:start_server"
stdio = "main:stdio_server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["services"]
py-modules = ["main", "cli"]

[dependency-groups]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "isort>=5.0",
]
